databases:
  - name: trackercoin
    databaseName: trackercoin
    user: trackercoin

services:
  - type: web
    name: TrackerCoin
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trackercoin
          property: connectionString
      - key: 8d697eb95f51001108d17a4fdd8013ca
        sync: false